name: people_mover
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
  
version: 1.0.0+1
  
environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.16.0"
  
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.32.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.17.5
  google_maps_flutter: ^2.9.0
  geolocator: ^10.1.1
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  google_sign_in: ^6.1.6
  sign_in_with_apple: ^5.0.0
  crypto: ^3.0.3
  local_auth: ^2.1.6
  local_auth_android: ^1.0.35
  local_auth_ios: ^1.1.5
  flutter_secure_storage: ^5.0.2
  sqflite: ^2.3.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  
dependency_overrides:
  collection: ^1.18.0
  web: ^0.5.1
  _flutterfire_internals: ^1.3.35
  firebase_core_platform_interface: ^5.0.0
  firebase_auth_platform_interface: ^7.0.0
  cloud_firestore_platform_interface: ^6.0.0
  
flutter:
  uses-material-design: true
  
  assets:
    - assets/icons/google.png
    - assets/icons/apple.png
  
  fonts:
    - family: OpenSans
      fonts:
      - asset: fonts/OpenSans-Regular.ttf
      - asset: fonts/OpenSans-Bold.ttf
        weight: 700
  
# The following configurations are not part of the pubspec.yaml file.
# They should be handled in their respective platform-specific files:
  
# For Android:
# Add these permissions to your AndroidManifest.xml
# <uses-permission android:name="android.permission.USE_BIOMETRIC" />
# <uses-permission android:name="android.permission.USE_FINGERPRINT" />
  
# For iOS:
# Add these keys to your Info.plist
# <key>NSFaceIDUsageDescription</key>
# <string>Why you are using Face ID</string>
# <key>NSLocationWhenInUseUsageDescription</key>
# <string>Why you are using location</string>
# <key>NSLocationAlwaysUsageDescription</key>
# <string>Why you are always using location</string>
# <key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
# <string>Why you are always using location</string>
